services:
  server:
    build: server
    image: server
    network_mode: host
    env_file:
      - server/.env
  image_storage:
    build: image_storage
    image: image_storage
    network_mode: host
    env_file:
      - image_storage/.env
  minio:
    image: minio/minio
    command: server /data/ --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
